-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Мар 29 2020 г., 11:22
-- Версия сервера: 10.4.11-MariaDB
-- Версия PHP: 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `dbexam`
--

-- --------------------------------------------------------

--
-- Структура таблицы `qalist`
--

CREATE TABLE `qalist` (
  `idQ` int(255) NOT NULL,
  `Question` varchar(5000) NOT NULL,
  `Answer` varchar(5000) NOT NULL,
  `Mark` int(11) NOT NULL,
  `idT` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `qalist`
--

INSERT INTO `qalist` (`idQ`, `Question`, `Answer`, `Mark`, `idT`) VALUES
(1, 'There are two types of RAM: dynamic RAM (DRAM) and static RAM (SRAM).\r\nFive statements about DRAM and SRAM are shown below.\r\nMatch the statements with it’s appropriate type of RAM\r\n1.requires data to be refreshed periodically in order to retain the data\r\n2.has more complex circuitry\r\n3.does not need to be refreshed as the circuit holds the data as long as the power supply is on\r\n4.requires higher power consumption which is significant when used in battery-powered devices\r\n5.used predominantly in cache memory of processors where speed is important\r\n\r\nDRAM-........................................................................\r\nSRAM-.....................................................................[5]\r\n', 'each correct matching gives 1 mark\r\n\r\nDRAM - 1 and 4 statements\r\nSRAM -  2,3 and 5 statements\r\n', 5, 1),
(2, 'Describe three differences between RAM and ROM.\r\n\r\n\r\n\r\n\r\n\r\n[3]', 'maximum of two marks for RAM and maximum of two marks for ROM\r\n\r\nRAM\r\n• loses contents when power turned off/volatile memory/temporary memory\r\n• stores files/data/operating system currently in use\r\n• data can be altered/deleted/read from and written to\r\n• memory size is often larger than ROM\r\nROM\r\n• doesn’t lose contents when power turned off/non-volatile memory/permanent memory\r\n• cannot be changed/altered/deleted/read only\r\n• can be used to store BIOS/bootstrap\r\n', 3, 1),
(3, 'DVD-RAM and flash memory are two examples of storage devices.\r\nDescribe two differences in how they operate.\r\n\r\n\r\n\r\n\r\n\r\n[2]\r\n', '\r\none mark for DVD-RAM, one mark for flash memory.\r\n\r\nDVD-RAM\r\n• data is stored/written using lasers/optical media\r\n• DVD-RAM uses phase changing recording, in which varying laser intensities cause\r\ntargeted areas in the phase change recording layer to alternate between an amorphous\r\nand a crystalline state.\r\n• uses a rotating disk with concentric tracks\r\n• allows read and write operation to occur simultaneously\r\nflash memory\r\n• most are NAND-based flash memory\r\n• there are no moving parts\r\n• uses a grid of columns and rows that has two transistors at each intersection\r\n• one transistor is called a floating gate\r\n• the second transistor is called the control gate\r\n• memory cells store voltages which can represent either a 0 or a 1\r\n• essentially the movement of electrons is controlled to read/write\r\n• not possible to overwrite existing data; it is necessary to first erase the old data then write the new data in the same location', 2, 1),
(4, 'Examples of primary and secondary storage devices include:\r\n• hard disk\r\n• DVD-RW\r\n• flash memory\r\nFor each device, describe the type of media used.\r\n\r\nHard disk\r\n\r\nDVD-RW\r\n\r\nFlash memory\r\n\r\n[3]\r\n', 'Hard disk – magnetic (storage media)\r\nDVD-RW – optical (storage media)\r\nFlash memory – solid state (memory device)\r\n', 3, 1),
(5, 'Describe the internal operation of the following devices:\r\n\r\nDVD-RW \r\n\r\n\r\n\r\nDVD-RAM\r\n\r\n\r\n\r\n[4]\r\n', 'DVD-RW[2]\r\n– uses a single spiral track\r\n– only allows write OR read operation to occur as separate operations\r\n– requires special packet reading/writing software\r\n– in order to write new data to the disc the existing data must be completely erased\r\n– performance degrades/becomes unreliable after 1000 record/erase cycles\r\n– single sided, 4.7Gb capacity\r\n– disc rotates at different speeds/constant linear velocity\r\nDVD-RAM[2]\r\n– uses several concentric tracks\r\n– allows simultaneous read/write operations\r\n– requires no special read/write software\r\n– makes use of sectors to store data\r\n– repeatedly read, write and erase/100000 record/erase cycles possible\r\n– single or double sided, 4.7Gb capacity per side\r\n– disc rotates at a constant speed/constant angular velocity\r\n', 4, 1),
(6, 'Three descriptions and two types of processor are shown below.\r\nType of processor: RISC and CISC\r\nWrite which description refer to appropriate type of processor. \r\nMakes extensive use of general purpose registers _____\r\nMany addressing modes are available ______\r\nHas a simplified set of instructions_______\r\n[3]\r\n', 'RISC\r\nCISC\r\nRISC                                                                            \r\n[Max 3]\r\n', 3, 1),
(7, 'Five modes of addressing and five descriptions are shown below.\r\nWrite which description refers to appropriate mode of addressing.\r\nModes of addressing:\r\ndirect,immediate,indexed,indirect,relative\r\n\r\nthe operand is the address of the\r\naddress of the value to be used__________\r\n\r\nthe operand is the address of the value to be used__________\r\n\r\nthe operand is the offset from the current address where the value to be used is stored__________\r\n\r\nthe operand plus the contents of the index register is the address of the value to be used__________\r\n\r\nthe operand is the value to be used__________\r\n[5]\r\n', 'indirect\r\ndirect\r\nrelative\r\nindexed\r\nimmediate\r\n', 5, 1),
(8, 'Name and describe three buses used in the von Neumann model.\r\nBus 1 -\r\nDescription\r\n\r\n \r\nBus 2 -\r\nDescription \r\n\r\n\r\nBus 3 -\r\nDescription \r\n\r\n\r\n[6]\r\n', 'one mark for name of bus + one mark for description\r\n\r\naddress bus\r\n• lines used to transfer address of memory or input/output location\r\n• unidirectional bus\r\n\r\ndata bus\r\n• used to transfer data between the processor and memory/input and output devices\r\n• bidirectional bus\r\n\r\ncontrol bus\r\n• used to transmit control signals\r\n• e.g. read/write/fetch/ ...\r\n• dedicated bus since all timing signals are generated according to control signal [6]\r\n', 6, 1),
(9, 'The sequence of operations shows, in register transfer notation, the fetch stage of the fetch-execute cycle.\r\n\r\n1. MAR ← [PC]\r\n2. PC ← [PC] + 1\r\n3. MDR ← [[MAR]]\r\n4. CIR ← [MDR]\r\n\r\n• [register] denotes contents of the specified register or memory location\r\n• step 1 above is read as “the contents of the Program Counter are copied to the Memory Address Register”\r\n\r\n(i) Describe what is happening at step 2.\r\n\r\n\r\n[1]\r\n(ii) Describe what is happening at step 3.\r\n\r\n\r\n[1]\r\n(iii) Describe what is happening at step 4.\r\n\r\n\r\n[1]\r\n(c)Describe what happens to the registers when the following instruction is executed: LDD 35\r\n\r\n\r\n\r\n[2]\r\n(d) (i)Explain what is meant by an interrupt.\r\n\r\n\r\n\r\n[2]\r\n(ii)Explain the actions of the processor when an interrupt is detected.\r\n\r\n\r\n\r\n\r\n[4]\r\n', '(i) the program counter is incremented [1]\r\n\r\n(ii) the data stored at the address held in MAR is copied into the MDR [1]\r\n\r\n(iii) the contents of the Memory Data Register is copied into the Current Instruction Register [1]\r\n\r\n(c) \r\n• the MAR is loaded with the operand of the instruction // loaded with 35\r\n• the Accumulator is loaded with the contents of the address held in MAR\r\n// the Accumulator is loaded with the contents of the address 35 [2]\r\n\r\n(d) (i) \r\n• a signal\r\n• from a device/program that it requires attention from the processor [2]\r\n\r\n(ii) \r\n• at a point during the fetch-execute cycle ...\r\n• check for interrupt\r\n• if an interrupt flag is set/ bit set in interrupt register\r\n• all contents of registers are saved\r\n• PC loaded with address of interrupt service routine [4]', 11, 1),
(10, 'A company develops software. It provides virtual machines for its software developers. The\r\ncompany has a large number of clients who use a wide range of hardware and software.\r\n\r\nExplain the term virtual machine. Ensure that your answer includes the terms hardware and software.\r\n\r\n\r\n\r\n[2]\r\n', 'Use of software ... (idea of using)\r\n\r\nto implement a hardware set-up (idea of implementing / simulating / emulating)\r\n', 2, 1),
(11, 'A company develops software. \r\n It provides virtual machines for its software developers. The company has a large number of clients who use a wide range of hardware and software.\r\n\r\nGive one benefit to the company of using virtual machines.\r\n\r\n[1]\r\n\r\nGive one drawback to the company of using virtual machines.\r\n\r\n\r\n[1]', 'Benefits:\r\n\r\nno need to acquire client hardware for testing /\r\nreduces set-up time for test system /\r\ncommon development system for all developers\r\n\r\nDrawbacks:\r\n\r\nsoftware emulation runs slower than real hardware /\r\nnot possible to emulate some hardware\r\n', 2, 1),
(12, 'Describe how special purpose registers are used in the fetch stage of the fetch-execute cycle.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'Four points from: \r\n• The Program Counter (PC) holds the address of the next instruction to be fetched\r\n• The address in the Program Counter (PC) is copied to the Memory Address Register\r\n(MAR)\r\n• The Program Counter (PC) is incremented\r\n• The instruction is copied to the Memory Data Register (MDR)\r\no .... from the address held in the Memory Address Register (MAR)\r\n• The instruction from the Memory Data Register (MDR) is copied to the Current\r\nInstruction Register (CIR)', 4, 1),
(13, 'The virtual machine software undertakes many tasks.\r\nDescribe two of these tasks.\r\n\r\n\r\n\r\n[2]\r\n', 'Examples:\r\n\r\nCreate / delete virtual machine\r\nExisting hardware made available to guest OS // hardware emulation\r\nEnsures each virtual machine is protected from actions of another virtual\r\nmachine\r\n', 2, 1),
(14, 'Explain the difference between a guest operating system and a host operating system.\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'Guest operating system:\r\n\r\nAn operating system running in a virtual machine //\r\nControls virtual hardware //\r\nOS is being emulated\r\n\r\nHost operating system:\r\nThe operating system that is actually controlling the physical hardware //\r\nthe operating system for the physical machine// the OS running the VM\r\nsoftware\r\nGuest OS is running under the Host OS software\r\n', 2, 1),
(15, 'A company uses a computer as a web server. The manufacturer will no longer support the\r\ncomputer’s operating system (OS) in six months’ time. The company will then need to decide\r\non a replacement OS.\r\nThe company is also considering changing the web server software when the OS is changed.\r\nWhenever any changes are made, it is important that the web server service is not disrupted.\r\nIn developing these changes, the company could use virtual machines.\r\nDescribe two possible uses of virtual machines by the company.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'Examples:\r\n\r\nTrial/use alternative replacement operating system(s) ...\r\nTest to identify possible problems\r\nMuch easier to create VM with a new OS than create new computer\r\nsystem\r\n\r\nTrial/use alternative replacement web server software ...\r\nTest to identify possible problems\r\nEasier to try alternative new software and new OS combinations\r\n\r\nTo provide some additional service(s)\r\nTrial/test its use - description e.g. a print server\r\n\r\nGeneral description point – to provide a safe environment during testing\r\n(which does not disrupt the web server service)', 4, 1),
(16, 'State what CPU stands for.\r\n\r\n\r\n[1]\r\n', 'Central processing unit', 1, 1),
(17, 'What is CPU?\r\n\r\n\r\n\r\n[2]\r\n', 'The central processing unit (CPU) is the unit which performs most of the processing inside a computer. To control instructions and data flow to and from other parts of the computer, the CPU relies heavily on a chipset, which is a group of microchips located on the motherboard.\r\n', 2, 1),
(18, 'Name the component of CPU\r\n1-\r\n2-\r\n[2]\r\n', 'Control Unit\r\nArithmetic Logic Unit \r\n', 2, 1),
(19, 'Which of the following expressions is in the sum-of-products (SOP) form?\r\na.(A + B)(C + D)\r\nb.(A)B(CD)\r\nc.AB(CD)\r\nd.AB + CD\r\n[1]\r\n', 'D', 1, 1),
(20, 'Simplify: C + BC:\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'C + BC\r\nC + (B + C)\r\n(C + C) + B\r\nT + B\r\nT\r\n', 2, 1),
(21, 'Simplify: A(A + B) + (B + AA)(A + B):\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[6]\r\n', 'A(A + B) + (B + AA)(A + B)\r\nAA + AB + (B + A)A + (B + A)B\r\nAB + (B + A)A + (B + A)B\r\nAB + BA + AA + BB + AB\r\nAB + BA + A + AB\r\nAB + AB + AT + AB\r\nAB + A(B + T + B)\r\nAB + A\r\nA + AB\r\n(A + A)(A + B)\r\nA + B\r\n', 6, 1),
(22, 'What Is Boolean Logic?\r\n\r\n\r\n\r\n[2]\r\n', 'Boolean Logic is a form of algebra which is centered around three simple words known as Boolean Operators: “Or,” “And,” and “Not”.\r\n', 2, 1),
(23, 'A game program is written which can be either interpreted or compiled. The table below shows five\r\nstatements about the use of interpreters and compilers.\r\nMatch the statements to its appropriate type of translator.\r\n\r\n1.This translator creates an executable file\r\n2.When this translator encounters a syntax error, game execution halts\r\n3.The translator analyses and checks each line just before executing it\r\n4.This translator will produce faster execution of the game program\r\n5.Use of this translator makes it more difficult for the user to modify the code of the game\r\n\r\nInterpreter:________\r\nCompiler:_________\r\n[5]\r\n', '\r\neach correct matching gives 1 mark\r\n\r\nInterpreter:2,3\r\nCompiler:1,4,5\r\n', 5, 2),
(24, 'Bobby is a senior programmer at a software house which produces intruder detection software.\r\nHe also runs his own software company which develops and sells various computer applications.\r\nWrite which activity is ethical or unethical.\r\n\r\ngives away passwords used in the intruder detection\r\nsoftware______________\r\n\r\nuses source code developed at the software house for the software he develops for his own company________\r\n\r\ninsists that staff work to deadlines________\r\n\r\nturns down training opportunities offered by his employer_________\r\n\r\nwrites and sells software that reads confidential data\r\nfrom client computers_________\r\n\r\nfakes test results of safety-critical software________\r\n\r\nhas the software applications developed overseas for sale in his own country____________\r\n[7]\r\n', '\r\nUnethical\r\nUnethical\r\nEthical\r\nUnethical\r\nUnethical\r\nUnethical\r\nEthical\r\n', 7, 2),
(25, 'The compilation process has a number of stages. The output of the lexical analysis stage forms the input to the next stage.\r\n\r\n(i) Name this stage.\r\n\r\n[1]\r\n\r\n(ii) State two tasks that occur at this stage.\r\n\r\n\r\n\r\n[2]\r\n', '(i) syntax analysis      \r\n                                                         \r\n(ii) any two points from: \r\n-construct parse tree // parsing \r\n-checking syntax/grammar\r\n-produce error report \r\n', 3, 2),
(26, 'The final stage of compilation is optimisation. There are a number of reasons for performing\r\noptimisation. One reason is to produce code that minimises the amount of memory used.\r\n(i) State another reason for the optimisation of code.\r\n\r\n[1]\r\n\r\n(ii) What could a compiler do to optimise the following expression?\r\nA ← B + 2 * 6\r\n\r\n\r\n\r\n[1]\r\n', '(i) Minimise the execution time // code runs faster [1]\r\n\r\n(ii) Compiler could calculate 2*6 and replace it with the value 12. [1]\r\n', 2, 2),
(27, '\r\nThese lines of code are to be compiled:\r\nX ← A + B\r\nY ← A + B + C\r\n\r\nFollowing the syntax analysis stage, object code is generated. The equivalent code, in assembly language, is shown below:\r\n\r\nLDD 436 //loads value A\r\nADD 437 //adds value B\r\nSTO 612 //stores result in X\r\nLDD 436 //loads value A\r\nADD 437 //adds value B\r\nADD 438 //adds value C\r\nSTO 613 //stores result in Y\r\n\r\nRewrite the equivalent code, given above, following optimisation.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'LDD 436 }\r\nADD 437 }                                                                           \r\nSTO 612 }\r\nADD 438                                                                             \r\nSTO 613                                                                             \r\n\r\n–1 for each additional instruction; 0 for copy of original code', 3, 2),
(28, 'Paul works part-time for a large software company. The company sells security software to a number of banks. He also runs his own software company that produces and sells computer games.\r\nSix statements about computer ethics are shown below.\r\nWrite which statement describes ethical or unethical behaviour.\r\n\r\nTo save time, Paul fakes the test results when testing the bank security software._____________\r\n\r\nPaul uses the software developed in his day job to help write some of the games software routines._____________\r\n\r\nTo allow him to concentrate on his games software, Paul has frequently turned down job opportunities in his day job._____________\r\n\r\nTo make the games software more realistic, Paul uses password protection code used in the bank security software._____________\r\n\r\nBecause his workload is increasing, Paul is now using overseas companies to write some of the routines used in his games software._____________\r\n\r\nPaul carries out training on how to write games software in his spare time._____________\r\n[6]\r\n', '\r\nUnethical\r\nUnethical\r\nEthical\r\nUnethical\r\nEthical\r\nEthical\r\n', 6, 2),
(29, 'A computer system in a control room is used to monitor earthquake activity.\r\nAn earthquake zone has a number of sensors to detect seismic activity.\r\nThe system detects when seismic activity is greater than 3 on the Richter Scale. Whenever this happens, a printer in the control room prints a report.\r\n\r\n(i) Identify the steps that are required in this monitoring system.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n\r\n(ii) When the system detects high activity, operators may need to respond rapidly. A printer is useful for hard copies, but may not be the best way to inform operators.\r\nGive a reason why.\r\n\r\n\r\n[1]\r\n(iii) Name an alternative output device for this monitoring system and give a reason for yourchoice.\r\nOutput device -\r\nReason for choice \r\n\r\n\r\n[2]', '(i) any four from:\r\n\r\n– sensors send signals / data to a computer\r\n– data / signal converted to digital (using an ADC)\r\n– computer calculates the activity value based on sensor signal strength / data\r\n– if calculated value > 3,\r\n– determine location of sensor\r\n– build up a map of seismic activity\r\n– location and magnitude sent to printer\r\n– ... via USB port / wireless link\r\n– monitoring is continuous [4]\r\n\r\n(ii) – output / hard copy not picked up in good time [1]\r\n\r\n(iii) 1 mark for name + 1 mark for reason for choice\r\n– speaker / buzzer / alarm bell\r\n– gives control room operators an audible warning\r\n– flashing lights\r\n– gives control room operators a visual warning\r\n– monitor\r\n– use of red / flashing colours on monitor gets the attention of operators [2]', 7, 2),
(30, 'Give the definition for each term:\r\n\r\nCompiler\r\n\r\n\r\n[1]\r\nAssembler\r\n\r\n\r\n[1]\r\nInterpreter\r\n\r\n\r\n[1]\r\n', 'Compiler:\r\nThe software reads the source code and reports all errors.\r\nThe software produces an executable file.\r\nor\r\nThe software translates a high level language program into machine code for the processor to execute\r\nAssembler:\r\nThe software translates low-level statements into machine code for the processor to execute.\r\n\r\nInterpreter:The software reads each statement and checks it before running it.The software halts when it encounters a syntax error.\r\nor\r\nThe software translates a high level language program into machine code for the processor to execute\r\n', 3, 2),
(31, '\r\nThere are 3 types of software licensing:\r\nOpen source,Shareware,Commercial.\r\n\r\nWrite relevant software licensing types to each description below.\r\n\r\nSoftware is purchased before it can be used_______\r\n\r\nSource code comes with the software_________\r\n\r\nSoftware is provided free on a trial basis_________\r\n\r\nThe software can be modified by the user________\r\n[4]\r\n', '1)Commercial\r\n2)Open source\r\n3)Shareware\r\n4)Open source\r\n', 4, 2),
(32, 'Describe two differences between a compiler and interpreter.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'Four from: \r\n• Compiler creates an executable//an interpreter does not create an executable.\r\n• The compiled program can be independently distributed.\r\n• Compiler reports all errors at the end of compilation//an interpreter stops when it reaches an error.\r\n• Interpreter executes each statement immediately after decoding/checking it//a compiler checks the whole program for errors.\r\n• The interpreter software/source code must be present in main memory every time the program is executed//the compiled program does not require compiler/source code to be present.\r\n• Cross-compilation is possible/compile on one hardware platform to run on another.\r\n', 4, 2),
(33, 'Explain what is meant by open source software.\r\n\r\n\r\n\r\n[2]\r\n', 'Two from: [2]\r\n• The source code comes with the software.\r\n• The user can edit the source code.\r\n• Once edited, the software is re-distributed with the changes.\r\n', 2, 2),
(34, 'Explain what is meant by commercial software.\r\n\r\n\r\n\r\n[2]\r\n', 'Two from: [2]\r\n• The software is purchased.\r\n• With a licence which restricts the number of users / possible time period for use.\r\n• The program code for the software cannot be edited.\r\n', 2, 2),
(35, 'A company needs new software to manage its accounts. It is evaluating two different options. One\r\noption is open source software and the other is commercial software.\r\nThe company has decided to purchase commercial software.\r\nIdentify four benefits to the company in choosing the commercial software option.\r\n1-\r\n\r\n\r\n2-\r\n\r\n\r\n3-\r\n\r\n\r\n4-\r\n\r\n\r\n[4]\r\n', 'Four from: \r\n• Support / training is readily available so help can be accessed if needed.\r\n• More robust software / fewer bugs as it has been tested more thoroughly/by more users.\r\n• Forums / user groups will exist for popular software.\r\n• Software upgrade path likely to be available (at minimal cost).\r\n• Manufacturer develops patches that can be automatically downloaded.\r\n• Compatibility is inbuilt for other commercial software.\r\n', 4, 2),
(36, 'Explain why a computer needs an operating system.\r\n\r\n\r\n\r\n[2]\r\n', 'Any two from\r\n\r\n• The hardware is unusable without an OS // hides complexity of hardware from user\r\n• Acts as an interface / controls communications between user and hardware /\r\nhardware and software\r\n• Provides software platform / environment on which other programs can be run \r\n', 2, 2),
(37, 'Give two key management tasks carried out by an operating system.\r\n\r\n1-\r\n\r\n\r\n2-\r\n\r\n\r\n[2]\r\n', 'Any two from:\r\n\r\n• Process / task / resource management\r\n• Main memory management\r\n• Peripheral / hardware / device management\r\n• File / secondary storage management\r\n• Security management\r\n• Provision of a software platform / environment on which other programs can be run\r\n', 2, 2),
(38, 'New program code is to be written in a high-level language. The use of Dynamic Link Library(DLL) files is considered in the design.\r\nDescribe what is meant by a DLL file.\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'Any two from:\r\n• A DLL file is a shared library file\r\n• Code is saved separately from the main .EXE files\r\n• Code is only loaded into main memory when required at run-time\r\n• The DDL file can be made available to several applications (at the same time) \r\n', 2, 2),
(39, 'The Java programming language is said to be machine or platform independent.\r\nDescribe what is meant by machine independent.\r\n\r\n\r\n[1]\r\nDescribe how a Java source code program is translated.\r\n\r\n\r\n\r\n\r\n[2]\r\n', '\r\nOne mark from:\r\n\r\n• The program code can be translated to run on any processor / platform\r\n• Source code is translated into machine independent intermediate code not\r\nmachine dependent code\r\n\r\nTwo marks from:\r\n\r\n• Java uses a two-step translation process\r\n• Java code is partially interpreted – partially compiled\r\n• Code is translated first into intermediate code / \"bytecode\"«\r\n• «using the Java compiler\r\n• The bytecode is finally interpreted by the Java Virtual Machine\r\n', 3, 2),
(40, 'Give the definition of the terms firewall and authentication. Explain how they can help with the security of data.\r\n\r\nFirewall \r\n\r\n\r\n\r\n[2]\r\nAuthentication \r\n\r\n\r\n\r\n\r\n[2]\r\n', 'maximum of two marks for firewall description + maximum of two marks for authentication description\r\n\r\nFirewall\r\n• sits between the computer or LAN and the Internet/WAN and permits or blocks traffic\r\nto/from the network\r\n• can be software and/or hardware\r\n• software firewall can make precise decisions about what to allow or block as it can detect\r\nillegal attempts by specific software to connect to Internet\r\n• can help to block hacking or viruses reaching a computer\r\n\r\nAuthentication\r\n• process of determining whether somebody/something is who/what they claim to be\r\n• frequently done through log on passwords/biometrics\r\n• because passwords can be stolen/cracked, digital certification is used\r\n• helps to prevent unauthorised access to data ', 4, 3),
(41, 'Describe two differences between data integrity and data security.\r\n\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'one mark for security, one mark for integrity:\r\n\r\n\r\n• integrity deals with validity of data/freedom from errors/data is reasonable\r\n• security deals with protection of data\r\n• security protects data from illegal access/loss\r\n• integrity deals with making sure data is not corrupted after, for example, being transmitted', 2, 3),
(42, 'Data integrity is required at the input stage and also during transfer of the data.\r\nState two ways of maintaining data integrity at the input stage. Use examples to help explain your answer.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'one mark for each way of maintaining data security + one mark for an example/enhancement\r\n\r\n\r\n• validation (to ensure data is reasonable)\r\n• examples include range checks, type checks, length checks, …\r\n\r\n• verification (checks if data input matches original/if transmitted data matches\r\noriginal)\r\n• can use double data entry or visual check/other methods such as parity checks\r\n• doesn’t check whether or not data is reasonable', 3, 3),
(43, 'Data integrity is required at the input stage and also during transfer of the data.\r\nState two ways of maintaining data integrity during data transmission. Use examples to help explain your answer.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'one mark for each way of maintaining data integrity + one mark for an example/enhancement\r\n\r\n• parity checking\r\n• one of the bits is reserved as parity bit\r\n• e.g. 1 0 1 1 0 1 1 0 uses odd parity\r\n• number of 1s must be odd\r\n• parity is checked at receiver’s end\r\n• a change in parity indicates data corruption\r\n\r\n• check sum\r\n• adds up bytes in data being sent and sends check sum with the data\r\n• calculation is re-done at receiver’s end\r\n• if not the same sum then the data has been corrupted during transmission', 3, 3),
(44, 'Data are to be transferred between two devices. Parity checks are carried out on the data.\r\nExplain what is meant by a parity check. Give an example to illustrate your answer.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'any four from:\r\n– parity can be even or odd\r\n– parity check uses the number of 1s in a binary pattern\r\n– if there is an even / odd number of 1s, then the parity is even / odd\r\n– following transmission ...\r\n– parity of each byte checked\r\n– a parity bit is used to make sure binary pattern has correct parity\r\n– example: 1 0 0 1 0 1 1 1 has parity bit set to 1 in MSB since system uses odd parity\r\n(original data: 0 0 1 0 1 1 1 which has four 1 bits)\r\n', 4, 3),
(45, 'Verification and validation can be applied during data entry.\r\nDescribe what is meant by these terms. For each method, explain why it is needed.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'Verification (one mark for description, one mark for explanation of need)\r\n– needed to ensure that the data entered exactly matches the original source/data is consistent\r\n– comparison of two versions of the data\r\n– examples include double entry, visual checking, proof reading etc...\r\n– does not check data is sensible/acceptable\r\nValidation (one mark for description, one mark for explanation of need)\r\n– needed to check that the data entered is sensible/reasonable/acceptable/matches required\r\ncriteria\r\n– automatic check by computer\r\n– examples include range, type, length, etc.\r\n– does not check data is correct Verification (one mark for description, one mark for explanation of need)\r\n– needed to ensure that the data entered exactly matches the original source/data is consistent\r\n– comparison of two versions of the data\r\n– examples include double entry, visual checking, proof reading etc...\r\n– does not check data is sensible/acceptable\r\nValidation (one mark for description, one mark for explanation of need)\r\n– needed to check that the data entered is sensible/reasonable/acceptable/matches required\r\ncriteria\r\n– automatic check by computer\r\n– examples include range, type, length, etc.\r\n– does not check data is correct\r\n', 4, 3),
(46, '(i) Describe two methods of preventing accidental loss of data.\r\n\r\n1 -\r\n\r\n\r\n2 -\r\n\r\n\r\n[2]\r\n(ii) Describe one way of ensuring the security of the data against malicious damage.\r\n\r\n\r\n\r\n[1]\r\n', '(i) Any two from:\r\n\r\n• frequent (or equivalent) backup EITHER to secondary media/to 3rd party\r\nserver/cloud/removable devices/continuous backup OR stored remotely\r\n• disk-mirroring strategy/RAID\r\n• UPS (uninterruptable power supply)/backup generator\r\n\r\n(ii) Any one from:\r\n\r\n• protection of data (or equivalent) with passwords/using password and username for\r\nlogging on include e.g. fingerprint scanning\r\n• encryption\r\n• installation and use of up to date anti-malware/anti-virus\r\n• give different access rights to different users\r\n• use a firewall,\r\n• physical methods/lock doors and use secure entry devices/CCTV\r\n', 3, 3),
(47, 'What are the purposes Pharming and Phishing?\r\n\r\nPhishing\r\n\r\n\r\n[1]\r\nPharming\r\n\r\n\r\n[1]\r\n', 'Phishing\r\nthrough email attempt to obtain somebody’s confidential data / install\r\nmalware\r\nPharming\r\nredirect website to fake website // domain name server compromised\r\n// proxy server compromised\r\n', 2, 3),
(48, 'Explain the following terms:\r\n\r\nEncryption\r\n\r\n\r\n[1]\r\nPublic key \r\n\r\n\r\n[1]', 'encryption: process of turning plain text into cipher text\r\n\r\npublic key: \r\nkey widely available that can be used to encrypt message that only owner of private key can decrypt \r\n// can be used to decrypt a message thereby confirming originator of message', 2, 3),
(49, 'A user downloads software from the Internet.\r\n(i) State what should be part of the download to provide proof that the software is authentic.\r\n\r\n\r\n[1]\r\n(ii) Describe the process for ensuring that the software is both authentic and has not been altered.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]', '(i) digital signature\r\n\r\n(ii)\r\n • software is put through hashing algorithm\r\n• hash total is encrypted with private key (digital signature)\r\n• software + encrypted hash / digital signature are sent\r\n• receiver is in possession of sender’s public key\r\n• the received hash total / digital signature is decrypted with public key(SH)\r\n• the receiver hashes received software (RH)\r\n• If SH matches RH then software is authentic and has not been altered', 5, 3),
(50, 'Explain the following terms:\r\n\r\nCipher text \r\n\r\n\r\n[1]\r\nPrivate key \r\n\r\n\r\n[1]', 'cipher text: encrypted text which is not understandable\r\n\r\nprivate key: key only known to owner that can be used to encrypt message to confirm author of message\r\n// can be used by owner to decrypt a message there by ensuring only owner can read message\r\n', 2, 3),
(51, 'Bill, a manager of a company, sent an email with very sensitive information to a work colleague,Alison. However, Bill also accidentally sent it to everybody in the company.\r\nDescribe the method used that ensured only Alison was able to read the original contents of\r\nthe email.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]', '• Manager encrypts email\r\n• using public key of colleague\r\n• colleague decrypts email\r\n• using his/her private key\r\n', 4, 3),
(52, 'Students email images to the radio station for use on its website.\r\nThese are compressed before sending using run-length encoding (RLE).\r\nExplain what is meant by run-length encoding.\r\n\r\n\r\n\r\n\r\n\r\n[3]', 'Three points from: \r\n\r\n• Lossless method of compression.\r\n• Reduces (the physical size of) a string of adjacent, identical characters/pixels / bytes\r\n• The repeating string (a run) is encoded into two values.\r\n• One value represents the number of (identical) characters in the run (the run count).\r\n• The other value is the code of the character / colour code of pixel etc. in the run (the\r\nrun value).\r\n• The run value and run count combination may be preceded by a control character.\r\n• Any valid example given.\r\n', 3, 3),
(53, 'State what DBMS stands for.\r\n\r\n[1]\r\n', 'Database Management System', 1, 3),
(54, 'A school stores a large amount of data. This includes student attendance, qualification, and\r\ncontact details. The school’s software uses a file-based approach to store this data.\r\n\r\nDescribe two ways in which the Database Administrator (DBA) could use the DBMS\r\nsoftware to ensure the security of the student data.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]', 'One mark for identifying the way in which the data security is ensured, and one mark for a further description.\r\n\r\nMaximum of two marks per method. Maximum of two methods. \r\n\r\nIssue usernames and passwords...\r\n- stops unauthorised access to the data\r\n- any further expansion e.g. strong passwords / passwords should be changed regularly etc…\r\n\r\nAccess rights / privileges…\r\n- so that only relevant staff / certain usernames can read/edit certain parts of the data\r\n- can be read only, or full access / read, write and delete\r\n- any relevant example e.g. only class tutors can edit detail of pupils in their tutor group\r\nCreate (regular / scheduled) backups...\r\n- in case of loss/damage to the live data a copy is available\r\n- any relevant example e.g. backing up the attendance registers at the end of each day and storing the data off-site/to a separate device\r\n\r\nEncryption of data...\r\n- if there is unauthorised access to the data it cannot be understood // needs a decryption key\r\n- any relevant example e.g. personal details of pupils are encrypted before being sent over the Internet to examination boards\r\n\r\nDefinition of different views...\r\n- composed of one or more tables\r\n- controls the scope of the data accessible to authorised users\r\n- any relevant example e.g. teachers can only see their classes\r\n\r\nUsage monitoring / logging of activity...\r\n- creation of an audit /activity log\r\n- records the use of the data in the database / records operations performed by all users / all access to the data\r\n- any relevant example, e.g. Track who changed a student’s grade', 4, 3),
(55, 'A school stores a large amount of data. This includes student attendance, qualification, and contact details. The school’s software uses a file-based approach to store this data.\r\nA feature of the DBMS software is a query processor.\r\nDescribe how the school secretary could use this software.\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'Two points from: \r\n\r\n• Set up search criteria\r\n• To find / retrieve / return the data that matches the criteria\r\n• Any relevant example e.g. find pupils who were absent on a particular day', 2, 3),
(56, 'The DBMS has replaced software that used a file-based approach with a relational database.\r\n\r\nDescribe how using a relational database has overcome the previous problems associated with a file-based approach.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'Three points from: [3]\r\n• By storing data in (separate) linked tables data redundancy is reduced / data duplication is controlled...\r\n• Compatibility / data integrity issues are reduced as data only needs to be updated once / is only stored once.\r\n• Unwanted or accidental deletion of linked data is prevented as the DBMS will flag an error.\r\n• Program - data dependence is overcome.\r\n• Changes made to the structure of the data have little effect on existing programs.\r\n• Ad-hoc / complex queries can be more easily made as the DBMS will have a query language/ QBE form.\r\n• Unproductive maintenance is eliminated as changes only need to be made once (rather than changing multiple programs).\r\n• Fields can be added or removed without any effect on existing programs (that do not use these fields).\r\n• Security / privacy of the data is improved as each application only has access to the fields it needs.\r\n• There is better control of data integrity as the DBMS (uses its Data Dictionary) to perform validation checks on data entered.\r\n', 3, 3),
(57, 'The database design has three tables to store the classes that students attend.\r\nSTUDENT(StudentID, FirstName, LastName, Year, TutorGroup)\r\nCLASS(ClassID, Subject)\r\nCLASS-GROUP(StudentID, ClassID)\r\nPrimary keys are not shown.\r\nThere is a one-to-many relationship between CLASS and CLASS–GROUP.\r\nDescribe how this relationship is implemented.\r\n\r\n\r\n\r\n\r\n\r\n[2]\r\n', '\r\nTwo points from: \r\n\r\n• The Primary Key in CLASS is ClassID\r\n• The Foreign Key of CLASS-GROUP is ClassID.\r\n• The Primary Key of CLASS is also included in CLASS-GROUP as a Foreign Key,\r\n(which links to CLASS table)\r\n\r\n\r\n', 2, 3),
(58, 'The database design has three tables to store the classes that students attend.\r\nSTUDENT(StudentID, FirstName, LastName, Year, TutorGroup)\r\nCLASS(ClassID, Subject)\r\nCLASS-GROUP(StudentID, ClassID)\r\nPrimary keys are not shown.\r\nThere is a one-to-many relationship between CLASS and CLASS–GROUP.\r\n\r\nDescribe the relationship between CLASS-GROUP and STUDENT.\r\n\r\n\r\n[1]\r\n', 'Many-to-one', 1, 3),
(59, 'The database design has three tables to store the classes that students attend.\r\nSTUDENT(StudentID, FirstName, LastName, Year, TutorGroup)\r\nCLASS(ClassID, Subject)\r\nCLASS-GROUP(StudentID, ClassID)\r\nPrimary keys are not shown.\r\nThere is a one-to-many relationship between CLASS and CLASS–GROUP.\r\n\r\nWrite an SQL script to display the StudentID and FirstName of all students who are in the tutor group 10B. Display the list in alphabetical order of LastName.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n\r\n\r\n', 'One mark per statement. Several statements may be on the same line. \r\n\r\nSELECT StudentID, FirstName\r\nFROM STUDENT\r\nWHERE TutorGroup = \"10B\" // WHERE (TutorGroup = \"10B\")\r\nORDER BY LastName ASC;', 4, 3),
(60, 'The database design has three tables to store the classes that students attend.\r\nSTUDENT(StudentID, FirstName, LastName, Year, TutorGroup)\r\nCLASS(ClassID, Subject)\r\nCLASS-GROUP(StudentID, ClassID)\r\nPrimary keys are not shown.\r\nThere is a one-to-many relationship between CLASS and CLASS–GROUP.\r\n\r\nWrite an SQL script to display the LastName of all students who attend the class whose ClassID is CS1.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', 'One mark per statement. Several statements may be on the same line. \r\n\r\nSELECT STUDENT.LastName\r\nFROM STUDENT, CLASS-GROUP\r\nWHERE ClassID = \"CS1\" // WHERE (ClassID = \"CS1\")\r\nAND CLASS-GROUP.StudentID = STUDENT.StudentID;\r\n\r\nOne mark per statement. Several statements may be on the same line.\r\n\r\nSELECT STUDENT.LastName\r\nFROM STUDENT INNER JOIN CLASS-GROUP\r\nON CLASS-GROUP.StudentID = STUDENT.StudentID\r\nWHERE ClassID = \"CS1\" // WHERE (ClassID = \"CS1\");', 4, 3),
(61, 'Give definition for each term:\r\n\r\nData dictionary\r\n\r\n\r\n\r\n[1]\r\nData security\r\n\r\n\r\n\r\n[1]\r\nData integrity\r\n\r\n\r\n\r\n[1]\r\n\r\n', 'Data dictionary \r\nA file/table containing all the data about the detail of the database design\r\n\r\nData security\r\nMethods of protecting the data including the uses of passwords and different access rights for different users of the database\r\n\r\nData integrity\r\nData design features to ensure the validity of data in the database\r\n', 3, 3),
(62, 'A school stores a large amount of data that includes student attendance, qualification and contact\r\ndetails. The school is setting up a relational database to store these data.\r\nThe school needs to safeguard against any data loss.\r\n\r\nDescribe three factors to consider when planning a backup procedure for the data.\r\nJustify your decisions.\r\n\r\n1-\r\n\r\n\r\n\r\n\r\n[2]\r\n\r\n2-\r\n\r\n\r\n\r\n\r\n[2]\r\n\r\n3-\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'One mark for procedure point, one mark for justification. [6]\r\nMaximum three procedures.\r\n• How often should the data be backed up? e.g. at the end of each day\r\n• Justification e.g. student’s progress may be edited each day and should not be lost\r\n• What medium should the data be backed up to? e.g. external hard disk drive\r\n• Justification e.g. it has large enough capacity\r\n• Where should the backups be stored? e.g. off-site\r\n• Justification e.g. so if the building is damaged only the original data are lost\r\n• What is backed up? e.g. only updated files ...\r\n• Justification e.g. There are a large number of files and they are not all updated each day\r\n• When should the backup take place? e.g. overnight\r\n• Justification e.g. the system is not likely to be used then\r\n• Who is responsible for performing the backup?\r\n• Justification e.g. otherwise it may not be done\r\n• Make sure the procedure is written down and understood by staff\r\n• Justification e.g. otherwise some data may not be backed up\r\n', 6, 3),
(63, 'A bank holds personal data about its customers and their financial data.\r\nDescribe three security measures that the bank could implement to protect its electronic\r\ndata.\r\n\r\nSecurity measure 1 -\r\nDescription \r\n\r\n\r\n\r\n[2]\r\nSecurity measure 2 -\r\nDescription \r\n\r\n\r\n\r\n[2]\r\nSecurity measure 3 -\r\nDescription .\r\n\r\n\r\n\r\n[2]\r\n', 'Three pairs from: [6]\r\n• Installing a firewall and ensuring it is switched on.\r\n• To stop unauthorised access / hackers gaining access to the bank’s computer network.\r\n\r\n• Use authentication methods such as passwords and usernames.\r\n• Passwords should be strong / biometrics.\r\n\r\n• Encrypt the data.\r\n• So that if data is accessed it will be meaningless / only accessed by those with decryption key.\r\n\r\n• Set up access rights...\r\n• To stop users reading/editing data they are not permitted to access.\r\n\r\n• Installing and running an up to date anti-malware program (anti-virus/anti-spyware etc.).\r\n• To detect / remove / quarantine viruses / key-loggers etc.\r\n\r\n• Make regular backups of the data.\r\n• To separate device or off site to enable recovery if necessary.\r\n\r\n• Employ measures for physical security.\r\n• Example of a measure for physical security.', 6, 3),
(64, 'A linked list abstract data type (ADT) is to be used to store and organise surnames.\r\nThis will be implemented with a 1D array and a start pointer. Elements of the array consist of a\r\nuser-defined type. The user-defined type consists of a data value and a link pointer.\r\n\r\nIdentifier      Data type   Description\r\n\r\nLinkedList      RECORD      User-defined type\r\nSurname         STRING      Surname string\r\nPtr             INTEGER     Link pointers for the linked list\r\n\r\nWrite pseudocode to declare the type LinkedList.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'Type LinkedList\r\nSurname:STRING\r\nPtr:INTEGER\r\n', 3, 3),
(65, '5 descriptions and 5 relational database terms are shown below.\r\nPut numbers to its appropriate definitions.\r\n\r\nCandidate key-\r\n\r\nEntity-\r\n\r\nForeign key-\r\n\r\nPrimary key-\r\n\r\nTable-\r\n\r\n[5]\r\n\r\n1.Any object, person or thing about which it is possible to store data\r\n\r\n2.Dataset organised in rows and columns; the columns form the structure and the rows form the content\r\n\r\n3.Any attribute or combination of attributes\r\nthat can act as a unique key\r\n\r\n4.Attribute(s) in a table that link to the primary key in another table to form a relationship\r\n\r\n5.Attribute or combination of attributes that is used to uniquely identify a record', '3\r\n1\r\n4\r\n5\r\n2', 5, 3),
(66, 'Explain what is meant by referential integrity.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'Any three from:\r\n• Ensures related data in tables are consistent\r\n• If one table has a foreign key (the ‘foreign’ table)...\r\n• ... then it is not possible to add a record to that table / the ‘foreign’ table\r\n• ... unless there is a corresponding record in the linked table with a corresponding\r\nprimary key (the ‘primary’ table)\r\n• Cascading delete\r\n• If a record is deleted in the ‘primary’ table...\r\n• all corresponding linked records in ‘foreign’ tables must also be deleted\r\n• Cascading update\r\n• If a record in the ‘primary’ table is modified...\r\n• ... all linked records in foreign tables will also be modified', 3, 3),
(67, 'Consider the URL:\r\nhttp://cie.org.uk/computerscience.html\r\nGive the meaning of the following parts of the URL.\r\n\r\nhttp -\r\n[1]\r\ncie.org.uk -\r\n[1]\r\ncomputerscience.html -\r\n[1]\r\n', 'http – enables browser to know what protocol is being used to access information in the domain\r\n\r\ncie.org.uk – cie.org.uk is the domain name\r\n\r\ncomputerscience.html – actual web page / file being viewed', 3, 4),
(68, 'Sometimes the URL contains the characters %20 and ?.\r\nDescribe the function of these characters.\r\n\r\n%20 -\r\n\r\n\r\n[1]\r\n\r\n? -\r\n\r\n\r\n[1]', '%20 – because <space> not allowed in a URL, %20 is the coding for a space (32 in denary)\r\n\r\n? – separates the URL from all parameters or variables', 2, 4),
(69, 'Describe what is meant by a client-server model of networked computers.\r\n\r\n\r\n\r\n\r\n[2]\r\n', '– at least one computer used to “serve” ...\r\n– ... other computers are referred to as “clients”\r\n– server provides services / applications etc. ...\r\n– ... which may be requested by clients\r\n', 2, 4),
(70, 'There are four statements about IP addresses.\r\nShow which of the statements are true or false.\r\n\r\nThe IP address consists of any number of digits separated by single dots (.)___\r\n\r\nEach number in an IP address can range from 0 to 255___\r\n\r\nIP addresses are used to ensure that messages and data reach their correct destinations___\r\n\r\nPublic IP addresses are considered to be more secure than private IP addresses___\r\n[4]      ', 'F\r\nT\r\nT\r\nF', 4, 4),
(71, 'A web page offers a link for users to request another web page. The requested web page contains HTML code and JavaScript code.\r\nPut the statements in correct order.\r\n\r\n1.The requested web page is displayed on the client computer____\r\n2.The user clicks on the hyperlink and the web page is requested from the web server_____\r\n3.The requested web page content is transmitted to the client computer_____\r\n4.The client computer processes the JavaScript code using the web browser software______\r\n5.The web server located the requested web page____\r\n[5]', 'each correct answer gives 1 mark\r\n\r\n2,5,3,4,1\r\n', 5, 4),
(72, 'An email is sent from one email server to another using packet switching.\r\nState two items that are contained in an email packet apart from the data.\r\n\r\n1 -\r\n\r\n[1]\r\n2 -\r\n\r\n[1]', 'Any point 1 mark\r\n\r\nsender’s IP address\r\nreceiver’s IP address\r\npacket sequence number\r\nchecksum\r\n', 2, 4),
(73, 'Explain the role of routers in sending an email from one email server to another.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'Any point 1 mark\r\n\r\nemail has been split up into packets\r\npacket has destination address\r\npackets pass through many different routers in journey\r\npackets don’t take same route\r\nrouters use IP addresses\r\npackets reassembled at destination to rebuild email\r\n', 3, 4),
(74, 'Sending an email message is an appropriate use of packet switching.\r\nExplain why this is the case.\r\n\r\n\r\n\r\n\r\n[2]\r\n', '\r\nAny point 1 mark\r\n\r\nemail message is only read when all of it is received\r\ntime delays due to lost/ delayed packets not significant\r\nso sending different packets by different routes is not issue/ is efficient\r\npackets arriving out of order not an issue\r\nno requirement for a continuous circuit (circuit switching)\r\n', 2, 4),
(75, 'Sending an email message is an appropriate use of packet switching,but it is not always an appropriate solution.\r\n\r\nName an alternative communication method of transferring data in a digital network.\r\n___________________[1]\r\n\r\nName an application for your method is an appropriate solution.\r\nJustify your choice.\r\nApplication ________________\r\n\r\nJustification - \r\n\r\n\r\n\r\n[3]\r\n', 'Circuit switching[1]                                                                 \r\n\r\nreal-time video/ video conferencing[1]                        \r\nAny point 1 mark\r\n\r\ncircuit made available is dedicated to this communication stream\r\nfull bandwidth available/ no sharing\r\nno lost packets\r\nguaranteed quality of service                                      \r\n[Max 2]', 4, 4),
(76, 'Explain what is meant by circuit switching.\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'dedicated circuit/channel/physical path \r\nwhich lasts for duration of connection\r\n\r\n\r\n', 2, 4);
INSERT INTO `qalist` (`idQ`, `Question`, `Answer`, `Mark`, `idT`) VALUES
(77, 'There are many applications in which digital data are transferred across a network. Video conferencing is one of these.\r\nFor this application, circuit switching is preferable to the use of packet switching.\r\nExplain why this is so.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[6]\r\n', 'e.g.\r\ncs: gives dedicated circuit [1]\r\nps: split into packets/chunks [1]\r\nps: sends packets on individual routes [1]\r\ncs: whole bandwidth available // ps: shares bandwidth [1]\r\ncs: faster data transfer [1]\r\ncs: packets arrive in order they are sent [1]\r\ncs: packets cannot get lost [1]\r\ncs: better for a real-time application [1]\r\nps: packets may arrive out of order so delay until packet order restored [1]\r\nps: packets may get lost so retransmission causes delays [1]\r\n[max. 6]', 6, 4),
(78, 'A web page is transferred from a web server to a home computer using the Internet.\r\nExplain how the web page is transferred using packet switching.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'web page divided into packets/chunks [1]\r\neach packet has destination address [1]\r\nrouter looks at IP address... [1]\r\nand decides where to send packet next for most efficient path [1]\r\npackets can take different routes [1]\r\nhome computer reassembles packets to rebuild web page[1]\r\n[max. 3]', 3, 4),
(79, 'Distinguish between the Internet and the World Wide Web (WWW).\r\n\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'maximum of two marks for Internet references and maximum of two marks for world wide web references\r\n\r\nInternet\r\n• massive network of networks/interconnected network of computer devices\r\n• Internet stands for Interconnected Networks\r\n• uses TCP/IP protocol\r\n\r\nWorld Wide Web (www)\r\n• is a collection of (multimedia) web pages/documents\r\n• ...stored on websites\r\n• http/protocols used to transmit data\r\n• web pages are written in HTML\r\n• URLs specify the location of the web pages\r\n• web documents are accessed using browsers\r\n', 3, 4),
(80, 'There are 3 types of LAN: Bus with terminators at each end,Star,Wireless.\r\n\r\nWrite appropriate LAN types near the descriptions below.\r\nEach description can have more than one answer.\r\n\r\nAny packet the listening computer receives may be part of a message for itself ___________\r\n\r\nConnection provided through an access point________\r\n\r\nA process for handling collisions has to be\r\nimplemented__________\r\n\r\nListening computer only receives packets that\r\nare addressed to itself_________\r\n[4]\r\n', 'bus with terminators at each end,wireless(1st description)[1]\r\nwireless(2nd description)[1]\r\nbus with terminators at each end,wireless(3rd description)[1]\r\nstar(4th description)[1]', 4, 4),
(81, 'A user downloads a file using the FTP protocol.\r\nExplain the function played by each of the following:\r\n(i) Server -\r\n\r\n\r\n\r\n[2]\r\n(ii) Command -\r\n\r\n\r\n\r\n[2]\r\n(iii) Anonymous -\r\n\r\n\r\n\r\n[2]\r\n', '(i) Server: central computer\r\nstores files that are to be downloaded\r\n\r\n(ii) Command: user can send action/instruction\r\n(or by example, e.g. change directory)\r\nthat are carried out on server\r\n\r\n(iii) Anonymous: allows user to access files\r\nuser does not need to identify themselves to server\r\n', 6, 4),
(82, 'Access to World Wide Web content uses IP addressing.\r\nState what IP stands for.\r\n\r\n\r\n[1]\r\n', 'Internet Protocol', 1, 4),
(83, 'There are four possible IP addresses.\r\nIndicate for each IP address whether it is valid or invalid and give a reason.\r\n\r\n3.2A.6AA.BBBB(Hexadecimal)\r\n\r\n\r\n[1]\r\n2.0.255.1(Denary)\r\n\r\n\r\n[1]\r\n6.0.257.6(Denary)\r\n\r\n\r\n[1]\r\nA.78.F4.J8(Hexadecimal)\r\n\r\n\r\n[1]\r\n', '1)Invalid\r\n• This is more than 32 bits\r\n2)Valid\r\n• There are 4 bytes, each 255 or below // All the values are in the range 0 - 255\r\n3)Invalid\r\n• 257 is above 255 // The third group is above 255\r\n4)Invalid\r\n• J is not a valid hexadecimal digit // J8 is not a valid Hex number', 4, 4),
(84, 'Describe two differences between public and private IP addresses.\r\n\r\n1 -\r\n\r\n\r\n\r\n[1]\r\n2 -\r\n\r\n\r\n\r\n[1]', 'Two points from: \r\n• Public address can be reached across the Internet.\r\n• Private address can only be reached internally/through the LAN/Intranet // private\r\naddress cannot be reached across the Internet.\r\n• NAT (Network Address Translation) is necessary for a private IP address to access the\r\nInternet directly.\r\n• A private address is more secure than a public address // A public address is less secure\r\nthan a private address.\r\n• Public addresses are provided by ISP / assigned by InterNIC // Private addresses are\r\nassigned by the router (of the network concerned).\r\n• Public addresses are unique (to the Internet) // Private addresses (are unique within their\r\nnetwork, but) can be duplicated within other (discrete) networks.\r\n• 10.0.0.1 to 10.255.255.254 and 172.16.0.1 to 172.31.255.254 and 192.168.0.1.to\r\n192.168.255.254 form the private address space // IP addresses from the private\r\naddress space are never assigned as public.\r\n', 2, 4),
(85, 'A device needs an IP address to connect to the Internet. IPv4 is the more common type of\r\nIP address.\r\nDescribe, using an example, the format of an IPv4 address.\r\n\r\n\r\n\r\n\r\n\r\n[3]\r\n', 'Two marks for description, one mark for correct example. [3]\r\n• Four numbers separated with ‘.’\r\n• Each number is between 0 and 255 / 00 and FF in Hex / stored in one byte.\r\n• 32 bits long\r\n• Correct example\r\n', 3, 4),
(86, 'A computer user keys in the Uniform Resource Locator (URL) of a web page into a web\r\nbrowser.\r\nDescribe how the browser uses the Domain Name Service (DNS) to display the web page.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n\r\n', 'Four from: [4]\r\n• URL is a reference address to a resource on the Internet.\r\n• The URL is passed to the nearest Domain Name Server (by browser software).\r\n• DNS server stores a database / list of URLs and matching IP addresses.\r\n• DNS (Name Resolver) looks for the URL in its database.\r\n• Finds the matching IP address and returns it to the originator.\r\n• Or if it cannot find it, it forwards to another Domain Name Server at a higher level.\r\n• (Original) DNS server adds the returned IP address to its cache.\r\n• (Original) DNS server returns the IP address to the browser.', 4, 4),
(87, 'Both clients and servers use the Secure Socket Layer (SSL) protocol and its successor, the\r\nTransport Layer Security (TLS) protocol.\r\nWhat is a protocol?\r\n\r\n\r\n\r\n\r\n[2]\r\n', 'A set of rules ... \r\ngoverning communications/transmission of data /sending and receiving data\r\n', 2, 4),
(88, 'Both clients and servers use the Secure Socket Layer (SSL) protocol and its successor, the\r\nTransport Layer Security (TLS) protocol.\r\n\r\nName the client application used in this context.\r\n-\r\n[1]\r\nName the server used in this context.\r\n-\r\n[1]', '\r\n(Web) browser / email client\r\nWeb server / email server\r\n', 2, 4),
(89, 'Identify two problems that the SSL and TLS protocols can help to overcome.\r\n\r\n1 -\r\n\r\n\r\n[1]\r\n2 -\r\n\r\n\r\n[1]\r\n', 'Security //example: for example, alteration of transmitted messages\r\nPrivacy // for example, only intended receiver can view data \r\nAuthentication // for example, trust in other party\r\n', 2, 4),
(90, 'A user has the following issues with the use of their personal computer (PC).\r\nFor each case, state the utility software which should provide a solution.\r\n\r\n(i) The user wants to send a large file as an attachment to an email. The user knows that the recipient’s Internet Service Provider (ISP) has a limit of 2MB for file attachments.\r\nUtility software solution: \r\n\r\n[1]\r\n(ii) The user is writing a book and is worried that the document files could get damaged or deleted.\r\nUtility software solution: \r\n\r\n[1]\r\n(iii) The computer has recently been slow to load large files. The user has deleted a large number of small files to try to solve the problem. A friend has advised that there is a procedure which should be regularly carried out to reorganise file storage on the hard\r\ndisk.\r\nUtility software solution: \r\n\r\n[1]\r\n(iv) The user clicked on an attachment in an unsolicited email. Since then, the computer has shown some unexplained behaviours.\r\nUtility software solution: \r\n\r\n[1]', '(i) File compression software\r\n(ii) Backup software\r\n(iii) Disk defragmenting software\r\n(iv) Anti-virus software\r\n', 4, 2),
(91, 'A multi-user computer system stores information about users. It uses a 1D array,\r\nUserNameArray, of type STRING. There are 100 elements in the array.\r\n\r\nThe format of the string in each element of the array is as follows:\r\n<UserID><UserName>\r\n• UserID is a six-character string of numerals.\r\n• UserName is a variable-length string.\r\n\r\nWrite pseudocode for a procedure, BubbleSort, to perform an efficient bubble sort on\r\nUserNameArray. The array is to be sorted in ascending order of UserID.\r\nYou should assume that UserNameArray has been declared as a global variable.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n[8]', 'PROCEDURE BubbleSort\r\nDECLARE Temp : STRING\r\nDECLARE FirstID, SecondID : INTEGER\r\nDECLARE NoSwaps : BOOLEAN\r\nDECLARE Boundary : INTEGER\r\nDeclare J : INTEGER\r\nBoundary ← 99\r\nREPEAT\r\nNoSwaps ← TRUE\r\nFOR J ← 1 TO Boundary\r\nFirstID ← UserNameArray[J]\r\nSecondID ← UserNameArray[J + 1]\r\nIF FirstID > SecondID\r\nTHEN\r\nTemp ← UserNameArray[J]\r\nUserNameArray[J] ← UserNameArray[J + 1]\r\nUserNameArray[J + 1] ← Temp\r\nNoSwaps ← FALSE\r\nENDIF\r\nENDFOR\r\nBoundary ← Boundary - 1\r\nUNTIL NoSwaps = TRUE\r\nENDPROCEDURE\r\n', 8, 2),
(92, 'The environment in a very large greenhouse is managed by a computer system. The system uses\r\na number of different sensors that include temperature sensors. In addition, the system controls a number of heaters, windows and sprinklers.\r\n\r\n(a) State one other type of sensor that could be used with this system.\r\nJustify your choice.\r\nSensor \r\n\r\nJustification \r\n\r\n\r\n[2]', 'One mark for suitable sensor, one mark for justification\r\nMax one sensor, max two marks\r\n\r\nhumidity\r\n« to ensure that the plants have the right level of moisture in the air\r\npressure / proximity\r\n\r\n« to detect whether the windows are open or closed condone ‘check’\r\nmoisture\r\n\r\n« to ensure the water levels in the soil are correct\r\nlight\r\n\r\n« to ensure the light levels in the greenhouse are correct for plant growth\r\n\r\n« to ensure the windows are closed when night falls\r\n', 2, 2),
(93, 'A small business has several computers, each with a single-user operating system.\r\n(a) State what is meant by single-user.\r\n\r\n[1]\r\n', '– only one user at a time', 1, 2),
(94, 'A supermarket uses barcodes on all its products.\r\nThe wages department at the supermarket runs the payroll program and produces employee wage slips each month. The payroll program uses batch processing.\r\n(i) State what is meant by batch processing.\r\n\r\n[1]\r\n\r\n(ii) Describe why batch processing is used in this application.\r\n\r\n\r\n\r\n[2]', '(i)system where all the data is first gathered together and then processed all in one go\r\n(without any human interaction)\r\n\r\n(ii) Any two from:\r\n\r\n• large volume of data\r\n• data is all of a similar type\r\n• not time sensitive (at end of month ...)\r\n• need to collect number of hours/overtime for each month first before the wages can\r\nbe calculated', 3, 2),
(95, 'Describe the difference between a command line interface (CLI) and a graphical user interface (GUI).\r\n\r\n\r\n\r\n\r\n[2]', '1 mark per point\r\nCLI\r\n• user types in instructions to open/launch an application\r\n• usually a number of instructions need to be typed in\r\n• user is in direct communication with the computer system\r\n• user has to type in the commands each time they want to open/launch the application\r\nGUI\r\n• user interacts with the system by using icons\r\n• user doesn’t need to know where application resides in the computer\r\n• the application is opened/launched by clicking on an icon using a mouse (e.g.)\r\n• windows is an example of GUI interface \r\n', 2, 2),
(96, 'CLI and GUI interfaces have advantages to certain users.\r\nDescribe which type of user would find each of the interfaces the most useful. Justify your choice.\r\n\r\nCLI\r\n\r\n\r\nGUI\r\n\r\n\r\n[2]', 'CLI\r\n• programmer/technician } need to access system and communicate\r\n• systems engineer } at system level\r\nGUI\r\n• end user } does not need computer knowledge\r\n} just click on the icon to launch the application [2]', 2, 2),
(97, 'The LAN is implemented and the manager suggests that the firm should introduce an\r\nintranet.\r\n(i) Describe what is meant by an intranet.\r\n\r\n\r\n[2]\r\n', 'Intranet ...\r\nInformation system using Internet protocols\r\nProvides service of web pages (to client computers)\r\n// stores content on a web server\r\nSystem only available to staff within the organisation', 2, 4),
(98, 'Explain what is meant by symmetric encryption.\r\n\r\n\r\n[2]', 'Symmetric encryption ...\r\nPlain text is changed\r\nInto a cipher text message\r\nusing an encryption algorithm\r\nThe same algorithm (and key) is used to decrypt the message\r\n', 2, 3),
(99, 'A web browser is used to request and display a page stored on an internet web server.\r\nExplain how each of the following items is used in this event.\r\n(i) Packet: \r\n\r\n\r\n[2]\r\n(ii) Router: \r\n\r\n\r\n[2]\r\n(iii) TCP/IP: \r\n\r\n\r\n[2]', 'Packet:\r\nBoth web page and web page request are split into packets \r\nEach packet is sent individually from device to device \r\n\r\nRouter:\r\nTransmit packets\r\nContain connections to many other routers\r\nWhen packets arrive at router, router decides where next to send packet\r\n\r\nTCP/IP:\r\nIs the protocol \r\nRules for communication between web server and browser', 6, 4),
(100, 'BitTorrent is a protocol used at the Application layer for the exchange of data.\r\n(i) State the network model used with this protocol.\r\n\r\n\r\n[1]\r\n\r\n(ii) State the use of BitTorrent.\r\n\r\n\r\n[1]\r\n\r\n(iii) Explain how the exchange of data is achieved using BitTorrent.\r\n\r\n\r\n\r\n\r\n\r\n\r\n[4]\r\n', '(i) Peer-to-peer\r\n(ii) File sharing\r\n(iii) Any four points from the following:\r\n• Torrent descriptor file is made available\r\n• File to be shared is split into pieces\r\n• BitTorrent client software made available to other peers / users / computers\r\nAllowing them to work as seeds or leeches.\r\nA peer can act as a ‘seed’ – used to upload pieces of a file\r\nPeer downloading file can get pieces from different seeds simultaneously\r\n• Once a peer has a piece of the file it can become a seed for the parts\r\ndownloaded\r\nLeeches download much more than they upload\r\n• Central server called a tracker keeps records of all the peers (‘swarm’) and\r\nthe parts of the file they have\r\nCan pause and restart at any time.\r\n', 6, 4);

-- --------------------------------------------------------

--
-- Структура таблицы `tlist`
--

CREATE TABLE `tlist` (
  `idT` int(11) NOT NULL,
  `NameT` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `tlist`
--

INSERT INTO `tlist` (`idT`, `NameT`) VALUES
(1, 'Computer systems'),
(2, 'Software'),
(3, 'Information systems'),
(4, 'Network');

-- --------------------------------------------------------

--
-- Структура таблицы `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Дамп данных таблицы `users`
--

INSERT INTO `users` (`id`, `username`, `password`, `created_at`) VALUES
(1, 'aibek', '$2y$10$Wr4e99YoTWg5djOFqkgWleGVOIrOz4VlxXiTmsGw7nbJvI24UCFNm', '2020-03-29 14:11:37');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `qalist`
--
ALTER TABLE `qalist`
  ADD PRIMARY KEY (`idQ`),
  ADD KEY `idT` (`idT`);

--
-- Индексы таблицы `tlist`
--
ALTER TABLE `tlist`
  ADD PRIMARY KEY (`idT`),
  ADD KEY `idT` (`idT`);

--
-- Индексы таблицы `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `qalist`
--
ALTER TABLE `qalist`
  MODIFY `idQ` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=110;

--
-- AUTO_INCREMENT для таблицы `tlist`
--
ALTER TABLE `tlist`
  MODIFY `idT` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT для таблицы `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `qalist`
--
ALTER TABLE `qalist`
  ADD CONSTRAINT `qalist_ibfk_1` FOREIGN KEY (`idT`) REFERENCES `tlist` (`idT`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
